name: taully
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.6 
  video_player: ^2.5.0
  # dependencias firestore 
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/imgtaully/Taully_remo.png
    - assets/videos/Taully_remo.mp4


